server: "server"

# Connects to the MySQL Database
MySQL:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  useSSL: true

filter:
  - "n+(i|1|l|;|:)+(g|4)+((e|3)+r+|a+|4+)"